### ISSUE TITLE
video_colorize_image_parallel.py missing?

### ISSUE THREAD

**Issue by gessyoo** [ColasGael/Automatic-Video-Colorization#1]
Hello, I'm trying to run this repro under Ubuntu 18.04.  Your instructions refer to the following command:

python3 video_colorize_image_parallel.py --filename <BW_video_filename> --input_dir <path_to_input_directory> --output_dir <path_to_output_directory>

I'm unable to locate the file "video_colorize_image_parallel.py" in your repro.  Could you please include the file or clarify your instructions, thanks.

**Comment by ColasGael** [comment]
Thank you for spotting this, the README has been updated.
The corresponding file is in the baseline folder "Deep-Learning-Colorization". The baseline applies the "Colorful Image Colorization" independently to each image of the folder.
Please see our report for more details.
